name = "MakieLayout"
uuid = "5a521ce4-ebb9-4793-b5b7-b334dfe8393c"
authors = ["Julius Krumbiegel", "Simon Danisch"]
version = "0.4.1"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
Animations = "27a7e980-b3e6-11e9-2bcd-0b925532e340"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"

[compat]
AbstractPlotting = "^0.9.14"
Animations = "^0.3"
Formatting = "^0.4"
Match = "^1"
Observables = "^0.2, 0.3"
PlotUtils = "0.6.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
